version: "3.8"

services:
  web:
    image: php:8.1-apache
    container_name: miweb
    ports:
      - "8081:80"
    volumes:
      - ./miweb:/var/www/html
    environment: 
      APACHE_DOCUMENT_ROOT: /var/www/html/public
